kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminRoleBinding
  # namespace: default
subjects:
  - kind: ServiceAccount
    name: admin
    apiGroup: ''
roleRef:
  kind: Role
  name: admin
  apiGroup: ""