apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  serviceAccountName: restricted-access
  # serviceAccountName: admin
  # serviceAccountName: cluster-admin
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command: ['sh', '-c', 'tail -f /dev/null']
  restartPolicy: Never
