apiVersion: v1
kind: Pod
metadata:
  name: delete-pod
spec:
  serviceAccountName: admin
  containers:
    - name: kubectl
      image: gkabitakis/kubernetes-rbac:latest
      args: ['delete']
      imagePullPolicy: Always
  restartPolicy: Never