kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-access
  # namespace: default
subjects:
  - kind: ServiceAccount
    name: restricted-access
    apiGroup: ''
roleRef:
  kind: Role
  name: restricted-access
  apiGroup: ''
